{{- if .Values.awsEnvSecrets.externalSecret.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.awsEnvSecrets.env_secret_name }}
spec:
  secretStoreRef:
    kind: {{ .Values.awsEnvSecrets.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.awsEnvSecrets.externalSecret.secretStoreRef.name }}
  refreshInterval: 1h
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: {{ .Values.awsEnvSecrets.env_secret_name }}
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .Values.awsEnvSecrets.externalSecret.secretPath }}
      metadataPolicy: None
{{- end }}
