{{- $awsEnvSecretEntries := ((include "universal-chart.awsEnvSecretEntries" . | fromYaml).items | default list) -}}
{{- range $index, $secret := $awsEnvSecretEntries }}
{{- if gt $index 0 }}
---
{{- end }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret.env_secret_name }}
spec:
  secretStoreRef:
    kind: {{ $secret.externalSecret.secretStoreRef.kind }}
    name: {{ $secret.externalSecret.secretStoreRef.name }}
  refreshInterval: 1h
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: {{ $secret.env_secret_name }}
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $secret.externalSecret.secretPath }}
      metadataPolicy: None
{{- end }}
