{{- $horizontal := include "universal-chart.autoscaling.horizontal" . | fromYaml -}}
{{- include "universal-chart.autoscaling.validateHorizontal" (dict "root" . "config" $horizontal) -}}
{{- if $horizontal.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "universal-chart.fullname" . | quote }}
  labels:
    {{- include "universal-chart.labels" . | nindent 4 }}
  {{- with $horizontal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "universal-chart.fullname" . }}
  minReplicas: {{ $horizontal.minReplicas }}
  maxReplicas: {{ $horizontal.maxReplicas }}
  {{- with $horizontal.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics:
    {{- with $horizontal.metrics }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- range $index, $rule := $horizontal.prometheusScalingRules }}
    {{- include "universal-chart.autoscaling.prometheusMetric" (dict "rule" $rule "index" $index) | nindent 4 }}
    {{- end }}
{{- end }}
