apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nes-node-web.fullname" . }}
  namespace:
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ include "nes-node-web.fullname" . }}
      release: nes-prod
  template:
    metadata:
      labels:
        app: {{ include "nes-node-web.fullname" . }}
        release: nes-prod
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
        - name: {{ include "nes-node-web.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ required "A valid App Version must be provided to .Values.version" .Values.version }}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: '300Mi'
              cpu: 100m
          ports:
            - containerPort: {{ required "A valid .Values.port entry is required!" .Values.port }}
              name: http
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
