apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nes-node-web.fullname" . }}
  # namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: "{{ .Values.serviceSubdomain }}.{{ .Values.clusterZone }}"
    http:
      paths:
      - path: {{ .Values.urlPrefix }}/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "nes-node-web.fullname" . }}
            port: 
              number: 80
              # number: {{ required "A valid .Values.port entry is required!" .Values.port }}
