apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nes-node-web.fullname" . }}
  # namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - secretName: {{ include "nes-node-web.fullname" . }}-tls
    hosts:
      - "{{ .Values.serviceSubdomain }}.{{ .Values.clusterZone }}"
  rules:
  - host: "{{ .Values.serviceSubdomain }}.{{ .Values.clusterZone }}"
    http:
      paths:
      - path: {{ .Values.urlPrefix }}/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "nes-node-web.fullname" . }}
            port: 
              number: {{ required "A valid .Values.port entry is required!" .Values.port }}
  {{- if .Values.ingress.rules }}
  {{- range $key, $value := .Values.ingress.rules }}
  - {{ $value | toYaml | indent 4 | trim }}
  {{- end }}  
  {{- end }}  