apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secrets.manager | default "aws-secretsmanager" }} {{- else }} "aws-secretsmanager" {{- end }}
spec:
  provider:
    aws:
      region: {{ .Values.region }}
      service: SecretsManager

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nes-node-web.fullname" . }}-external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ if .Values.secrets -}} {{ .Values.secrets.manager | default "aws-secretsmanager" }} {{- else }} "aws-secretsmanager" {{- end }}
    kind: SecretStore
  target:
    name: {{ include "nes-node-web.fullname" . }}-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: nes/apps/{{ .Values.secrets.lane }}/{{ include "nes-node-web.fullname" . }}/secrets