apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ if .Values.secrets -}} {{ .Values.secrets.manager | default "aws-secretsmanager" }} {{- else }} "aws-secretsmanager" {{- end }}
spec:
  provider:
    aws:
      region: {{ .Values.region }}
      service: SecretsManager

{{ if .Values.secrets -}}
{{ range .Values.secrets.external.sources }}

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .store }}
    kind: SecretStore
  target:
    name: {{ .target }}
    creationPolicy: Owner
    {{ if .type -}}
    template:
      type: {{ .type }}
    {{- end }}
  dataFrom:
  - extract:
      key: {{ .key }}
      conversionStrategy: Default
      decodingStrategy: Auto
      metadataPolicy: None

{{- end }}
{{- end }}