apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: helm-charts-ack-opensearch-provider
  title: ack-opensearch-provider
  description: Helm chart for ACK-managed OpenSearch domains and exported connection secrets.
  annotations:
    github.com/project-slug: neverendingsupport/helm-charts
    backstage.io/techdocs-ref: dir:.
  tags:
    - helm
    - kubernetes
    - aws
    - opensearch
    - infrastructure
spec:
  type: library
  lifecycle: production
  owner: group:default/infrastructure
