replicaCount: 2

region: us-west-2

image:
  pullPolicy: Always
  tag: ""
  
port: ""
host: ""
version: ""
urlPrefix: ""

ingress:
  className: nginx
  rules: []

release: "deployed"

liveness:
  path: "/"
  enabled: true 
  initialDelay: 7
  period: 5
  timeout: 1
  thresholds: 
    success: 1
    failure: 10

deployment:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 1

resources:
  limits:
  requests:

# env:
#   - name: SOME_SVC_SECRET
#     valueFrom:
#       secretKeyRef:
#         name: some-secret
#         key: svc-env-value

# volumes:
#   mounts:
#     - name: example-volume
#       mountPath: /home/node/app/example.json
#       subPath: secret-subprop
#       readOnly: true
#   definitions: 
#     - name: example-volume
#       secret: 
#         secretName: secret-name