replicaCount: 1

image:
  pullPolicy: Always
  tag: ""
  
port: ""
host: ""
version: ""
urlPrefix: ""

# env:
#   - name: SOME_SVC_SECRET
#     valueFrom:
#       secretKeyRef:
#         name: some-secret
#         key: svc-env-value