apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: helm-charts-ingress-nginx
  title: ingress-nginx
  description: Never Ending Support ingress-nginx controller for Kubernetes.
  annotations:
    github.com/project-slug: neverendingsupport/helm-charts
    backstage.io/techdocs-ref: dir:.
  tags:
    - helm
    - kubernetes
    - ingress
    - nginx
    - nes
spec:
  type: library
  lifecycle: production
  owner: group:default/infrastructure
