{{- if and .Values.connectionSecret.create (not .Values.sequencedConnection.enabled) }}
{{- $annotations := include "ack-opensearch-provider.connectionSecretAnnotations" . | trim }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ack-opensearch-provider.connectionSecretName" . }}
  labels:
    {{- include "ack-opensearch-provider.labels" . | nindent 4 }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.connectionSecret.keys.username }}: {{ .Values.auth.username | quote }}
  {{ .Values.connectionSecret.keys.port }}: {{ ternary 443 80 (.Values.domainEndpointOptions.enforceHTTPS | default true) | quote }}
  {{ .Values.connectionSecret.keys.url }}: ""
  {{ .Values.connectionSecret.keys.authURL }}: ""
  {{- if eq .Values.auth.mode "irsa" }}
  {{ .Values.auth.password.key }}: ""
  {{- if .Values.auth.irsaRoleArn }}
  AWS_ROLE_ARN: {{ .Values.auth.irsaRoleArn | quote }}
  {{- end }}
  {{- end }}
{{- end }}
