{{- if and .Values.connectionSecret.create (not .Values.sequencedConnection.enabled) }}
{{- $annotations := include "ack-elasticache-provider.connectionSecretAnnotations" . | trim }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ack-elasticache-provider.connectionSecretName" . }}
  labels:
    {{- include "ack-elasticache-provider.labels" . | nindent 4 }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.connectionSecret.keys.username }}: {{ .Values.auth.username | quote }}
  {{ .Values.connectionSecret.keys.port }}: {{ default 6379 .Values.port | quote }}
  {{ .Values.connectionSecret.keys.tls }}: {{ (.Values.transitEncryptionEnabled | default false) | quote }}
  {{ .Values.connectionSecret.keys.url }}: ""
  {{ .Values.connectionSecret.keys.authURL }}: ""
  {{- if ne .Values.auth.mode "password" }}
  {{ .Values.auth.password.key }}: ""
  {{- end }}
{{- end }}
